### ISSUE TITLE
Missing or incorrect reference to document

### ISSUE THREAD

**Issue by glw** [fpdcc/document-search#64]
Missing PDF here:

https://documents.fpdccdata.com/flatdrawings/8770/

Download error:
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>FLAT_DRAWINGS/00008770.PDF</Key>
</Error>

**Comment by glw** [comment]
A couple more...

https://documents.fpdccdata.com/flatdrawings/8768/
https://documents.fpdccdata.com/flatdrawings/8769/

**Comment by jeancochrane** [comment]
This was an interesting bug! It turns out that some PDFs have the lowercase file extension `.pdf` instead of `.PDF`, but the source metadata lists all PDFs as having the uppercase extension `.PDF`. Renaming the PDFs to use the uppercase extension fixes the issue. I went ahead and did a quick search of the production S3 bucket and identified a couple of other documents that had this problem as well. Seems like everything is fixed now.

**Comment by glw** [comment]
Great! Thanks @jeancochrane !
